baseURL = "https://lxxxvi.github.io/hit-happens/"
languageCode = "de-ch"
title = "Hit Happens"
theme = "archie"
publishDir = "docs"

[markup]
  [markup.highlight]
    style = "monokailight"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/marioschuettel/"
