baseURL = "https://hithappens.lxxxvi.ch/"
languageCode = "de-ch"
title = "Hit Happens"
theme = "archie"

[markup]
  [markup.highlight]
    style = "monokailight"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/marioschuettel/"
